spring.application.name=Internship_Authentication_Service

spring.datasource.url=jdbc:postgresql://localhost:5434/auth_db
spring.datasource.username=users
spring.datasource.password=33563356
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/changeSet/changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate